var fase = [
	[
	new Question("Briófitas e pteridófitas apresentam várias características em comum, mas também diferem em muitos aspectos.</br>Assinale a característica que pertence a apenas um desses grupos de plantas.", ["Crescer preferencialmente em solos úmidos e sombreados.", "Necessitar de água para reproduzir-se.", "Não ter flores, sementes e frutos.", "Ser portadora de tecidos de transporte."], "Ser portadora de tecidos de transporte.", ""),
	new Question("Considere os seguintes organismos:</br>I.Algas</br>II.Briófitas</br>III.Pteridófitas</br>IV.Angiospermas</br>Gametas masculinos flagelados, que necessitam de água para encontrar os gametas femininos, são encontrados SOMENTE em:", ["I e II", "III e IV", "I, II e III", "I, III e IV"], "I e II", ""),
	new Question("Neste ano o Jardim Botânico do Rio de Janeiro completa 200 anos de existência. Nele estão situados acervos de mais de 8.000 espécies de plantas nacionais e de várias partes do mundo. O Jardim Botânico foi expandido em 15.000m2 e as estufas das orquídeas, bromélias, cactos e das plantas insetívoras foram reformadas. Este último grupo de plantas, também conhecido como plantas carnívoras, chama muito a atenção por poder obter nutrientes dos animais que capturam e digerem. Entretanto, os organismos do Reino Plantae são classificados quanto a sua nutrição como autótrofos.</br>Os organismos autótrofos são aqueles que sintetizam moléculas orgânicas a partir de:", ["água e glicose", "substâncias orgânicas", "água e CO2", "água, O2 e proteínas"], "água e CO2",""),
	new Question("Uma fruta podre no cesto pode estragar todo o resto.", ["Etileno", "Auxina", "Citocinina", "Giberelina"], "Etileno", ""),
	new Question("São processos biológicos relacionados diretamente a transformações energéticas celulares:", ["respiração e fotossíntese.", "digestão e excreção.", "respiração e excreção.", "digestão e osmose."], "respiração e fotossíntese.", ""),
	new Question("As trocas gasosas, ao nível das folhas, ocorrem através de numerosas aberturas epidérmicas denominadas:", ["Parênquimas", "Estômatos", "Células-guarda", "Acúleos"], "Estômatos", ""),
	new Question("Em pesquisas desenvolvidas com eucaliptos, constatou-se que a partir das gemas de um único ramo pode-se gerar cerca de 200.000 novas plantas, em aproximadamente duzentos dias; enquanto os métodos tradicionais permitem a obtenção de apenas cerca de cem mudas a partir de um mesmo ramo.</br>A cultura de tecido é feita a partir:", ["de células meristemáticas.", "de células da epiderme.", "de células do lenho.", "de células do súber."], "de células meristemáticas.", ""),
	new Question("As células vegetais jovens (meristemáticas) possuem inúmeras e pequenas bolsas membranosas que se fundem com o amadurecimento celular e em cujo interior encontra-se uma solução aquosa de proteínas, açúcares, íons inorgânicos, pigmentos hidrossolúveis e enzimas hidrolíticas.</br>Essas estruturas são:", ["os vacúolos.", "os lisossomos.", "os cloroplastos.", "o complexo de Golgi."], "os vacúolos.", ""),
	new Question("No corpo de uma planta superior, qual é o tecido que apresenta numerosas mitoses, sendo sempre formado por células indiferenciadas?", ["parênquima paliçádico", "colênquima angular", "colênquima tabular", "meristema primário"], "meristema primário", ""),
	new Question("Cortando-se, em forma de anel, a casca do caule de uma planta, a parte situada entre o corte e a raiz não é nutrida e morre.</br>O fluxo de seiva elaborada, com substâncias nutritivas, ocorre, das folhas para a raiz, no:", ["Xilema", "Meristema", "Floema", "Parênquima"], "Floema", ""),
	new Question("São importantes tecidos de sustentação dos vegetais:", ["Floema e xilema.", "Súber e ritidoma.", "Colênquima e esclerênquima.", "Parênquima de reserva."], "Colênquima e esclerênquima.",""),
	/*new Question("É característica típica das plantas terrestres vasculares e presença de folhas, que constituem expansões laminares verdes, especializadas na função fotossintética. No entanto, em ambientes áridos, encontram-se muitas vezes plantas sem evidência de folhas e com espinhos, como as cactáceas.</br>Esta característica tem relação com o habitat porque permite:", ["uma adaptação temporária até que o ambiente mude.", "um aumento da taxa de fotossíntese e de matéria orgânica formada.", "um aumento das velocidades de fotossíntese e transpiração.", "uma adaptação especial voltada à diminuição na perda d’água."], "uma adaptação especial voltada à diminuição na perda d’água.", "")
	new Question("Árvores adultas geralmente apresentam dificuldades para serem transplantadas de um lugar para outro. As palmeiras, pertencentes às monocotiledôneas, suportam melhor essa operação, devido ao seu sistema radicular, que é do tipo:", ["pivotante.", "fasciculado.", "escora.", "tabular."], "fasciculado.",""),
	new Question("Até cerca de 405 milhões de anos atrás, parece que a vida esteve limitada à água. A existência terrestre trouxe consigo sérios problemas como, por exemplo, o risco de dessecamento. Características que permitissem aos vegetais a redução de perda d’água em suas partes aéreas foram selecionadas positivamente pelo ambiente por facilitar a adaptação. A economia de água é permitida pelo seguinte tecido vegetal:", ["súber.", "floema.", "colênquima.", "parênquima de assimilação."], "súber.",""),
	new Question("Plantas que têm caules suculentos, folhas reduzidas e sistema radicular extenso, estão adaptadas para viver em:", ["ambiente aquático.", "regiões semi-áridas.", "regiões úmidas.", "solo com alto teor salino"], "regiões semi-áridas.",""),
	new Question("A sobrevivência de qualquer espécie depende de sua capacidade de deixar descendentes. No decorrer do processo evolutivo as plantas desenvolveram inúmeras adaptações para a disseminação de frutos e sementes. O fruto adaptado à dispersão pela água é o:", ["dente-de-leão.", "coco-da-baía.", "frutos de carrapicho.", "tomate."], "coco-de-baía.",""),
	new Question("O Parque Moscoso - marco histórico da cidade de Vitória - foi reformado e entregue à população capixaba. Passeando por suas alamedas, é comum encontrar troncos de árvores cobertos de musgos e seus galhos contendo samambaias, bromélias e orquídeas. Em alguns lugares, observam-se árvores com flores grandes, vermelhas, com néctar abundante e pouco viscoso. Essas características das flores indicam que a polinização nessa espécie é feita:", ["pelo vento e pela água.", "por insetos e pela luz.", "pelo vento e por mamíferos.", "por aves e por insetos."], "por aves e por insetos.",""),
	new Question("", ["", "", "", ""], ""),
	new Question("", ["", "", "", ""], ""),
	new Question("", ["", "", "", ""], ""),
	new Question("", ["", "", "", ""], ""),
	new Question("", ["", "", "", ""], ""),
	new Question("", ["", "", "", ""], ""),
	new Question("", ["", "", "", ""], ""),
	new Question("", ["", "", "", ""], ""),
	new Question("", ["", "", "", ""], "")*/
	],

	//fase2
	[
	new Question("Na passagem evolutiva de plantas aquáticas (algas verdes) para o ambiente terrestre, alguns cientistas consideram as briófitas as primeiras a apresentarem características que permitiram que as plantas invadissem esse tipo de ambiente.</br>No referido grupo (briófitas), uma dessas características é o(a):", ["aparecimento da clorofila dando início ao processo de fotossíntese.", "surgimento de tecidos de condução.", "formação de sementes como o modo mais eficiente de propagãção.", "surgimento de rizoides, que assumiram as funções de absorção e fixação."], "surgimento de rizoides, que assumiram as funções de absorção e fixação.", ""),
	new Question("São características das briófitas:", ["fase gametofítica dominante, esporófito dependente do gametófito, fecundação dependente da água.", "fase esporofítica dominante, gametófito dependente do esporófito, fecundação dependente da água.", "fase gametofítica dominante, esporófito independente do gametófito, fecundação independente da água.", "fase esporofítica dominante, gametófito independente do esporófito, fecundação independente da água."], "fase gametofítica dominante, esporófito dependente do gametófito, fecundação dependente da água.", ""),
	new Question("Uma garota estava observando a samambaia de sua mãe quando percebeu que todas as folhas estavam cheias de pontos escuros na face inferior. Achando que a planta em questão estava estragada, a menina arrancou todas as folhas da planta. De acordo com seus conhecimentos sobre pteridófitas, marque a alternativa que explica corretamente o que são os pontos pretos na folha.", ["Os pontos escuros na face inferior da folha são os chamados báculos, estruturas reprodutoras.", "Os pontos escuros na face inferior da folha são os chamados soros, estruturas que surgem em resposta a um ataque de fungos patogênicos.", "Os pontos escuros na face inferior da folha são os chamados soros, estruturas onde são produzidos os esporos.", "Os pontos escuros na face inferior da folha são os prótalos, a fase gametofítica da samambaia."], "Os pontos escuros na face inferior da folha são os chamados soros, estruturas onde são produzidos os esporos.", ""),
	new Question("O desenho a seguir representa uma folha de samambaia. A estrutura indicada pela seta é chamada…., sendo formada por um conjunto de….</br>Qual a alternativa que completa corretamente as lacunas acima?", ["soro, esporângios.", "esporângio, soros.", "antera, pólen.", "espongióforo, esporos."], "soro, esporângios.", ""),
	new Question("Várias hipóteses foram desenvolvidas para explicar a evolução das plantas. O critério que corrobora a hipótese evolutiva, a mais aceita atualmente, utiliza a dependência da água para que possa ocorrer o processo de fecundação. Sobre esse processo, é correto afirmar que", ["as plantas que não dependem da água para se reproduzirem são briófitas, gimnospermas e espermatófitas.", "as briófitas e pteridófitas necessitam da água, pois produzem anterozoides que necessitam “nadar” até a oosfera.", "as plantas avasculares não precisam da água para a reprodução, possuem tecidos diferenciados que possibilitam dominar o ambiente terrestre.", "todas as plantas necessitam da água para a reprodução, inclusive as fanerógamas, assim, esse critério não deveria ser utilizado."], "as briófitas e pteridófitas necessitam da água, pois produzem anterozoides que necessitam “nadar” até a oosfera.", ""),
	new Question("Uma das características mais marcantes das gimnospermas é a presença das sementes. Essa estrutura, presente também nas angiospermas, é responsável por proteger o embrião e garantir sua nutrição. Marque a alternativa que indica corretamente a estrutura que origina a semente.", ["A semente é formada a partir do desenvolvimento do ovário.", "A semente é formada a partir do desenvolvimento do óvulo.", "A semente é formada a partir do desenvolvimento do carpelo.", "A semente é formada a partir do desenvolvimento do esporo."], "A semente é formada a partir do desenvolvimento do óvulo.", ""),
	new Question("Considere as características relacionadas abaixo:</br>I.Grãos de pólen;</br>II.Sistema vascular;</br>III.Sementes;</br>IV.Fruto.</br>São características comuns às gimnospermas e angiospermas:", ["apenas I e III.", "apenas I e IV.", "II, III e IV.", "I, II e III."], "I, II e III.", ""),
	new Question("O endosperma da semente de angiospermas contém:", ["Material genético de cada genitor em quantidades iguais.", "Somente material genético materno.", "Maior quantidade de material genético materno.", "Maior quantidade de material genético paterno."], "Maior quantidade de material genético materno.", ""),
	new Question("Sabemos que a coifa é uma estrutura encontrada na extremidade da raiz. Ela é formada por células parenquimáticas vivas que revestem o órgão como se fossem um dedal. A respeito das funções dessa estrutura, marque a alternativa incorreta.", ["A coifa ajuda a raiz a penetrar no solo.", "A coifa protege o ápice da raiz do atrito com o solo.", "A coifa está relacionada com a proteção contra o ataque de micro-organismos.", "A coifa atua promovendo a absorção de água e de nutrientes."], "A coifa atua promovendo a absorção de água e de nutrientes.", ""),
	new Question("A figura abaixo mostra várias folhas de milho. Observe que elas apresentam uma porção terminal bastante desenvolvida que abraça o caule. Essa estrutura é denominada de:", ["pecíolo.", "limbo.", "bainha.", "estípula."], "bainha.", "fase2-q10.png")
	]

	//fase3
	[
	new Question("O endosperma primário é tecido de reserva encontrado nas sementes de gimnospermas (pinheiros). Na formação deste tecido entra(m):", ["apenas tecido de origem materna uma vez que é haplóide;", "tecidos de origem materna e paterna formando um tecido diplóide;", "tecidos de origem materna e paterna, respectivamente na proporção 2 : 1, já que é triplóide;", "tecidos de origem paterna e materna, respectivamente na proporção 2 : 1, já que é triplóide"], "tecidos de origem materna e paterna, respectivamente na proporção 2 : 1, já que é triplóide;",""),
	new Question("Um estudante fez as seguintes afirmações com relação ao pinheiro-do-paraná:</br>I.Pertence ao grupo das gimnospermas, plantas que produzem sementes nuas.</br>II.O fruto, conhecido como pinhão, é comestível.</br>III.As flores encontram-se reunidas em inflorescências compactas.</br>IV.O caule é um rizoma.</br>São corretas as afirmações:", ["I e IV", "II e III", "II e IV", "I e III"], "I e III", ""),
	new Question("Geralmente, caules subterrâneos que acumulam substâncias nutritivas, denominados tubérculos, são confundidos como sendo raízes tuberosas que também acumulam reserva de amido. Um caso típico desse equívoco seria o de classificar a batata-inglesa como raiz tuberosa. Qual das alternativas apresenta uma característica que diferencia um tubérculo de uma raiz tuberosa?", ["O tubérculo possui pelos absorventes para a absorção de água.", "A raiz tuberosa possui gemas axilares para o crescimento de ramos.", "A raiz tuberosa possui gemas apicais para desenvolver novas raízes.", "O tubérculo possui gemas laterais para desenvolver ramos e folhas."], "O tubérculo possui gemas laterais para desenvolver ramos e folhas.", ""),
	new Question("Dentre outras características, uma determinada vegetação apresenta folhas durante três a quatro meses ao ano, com limbo reduzido, mecanismo rápido de abertura e fechamento dos estômatos e caule suculento. Essas são algumas características adaptativas das plantas ao bioma onde se encontram.<br>Que fator ambiental é o responsável pela ocorrência dessas características adaptativas?", ["Escassez de nutrientes no solo.", "Estratificação da vegetação.", "Baixo pH do solo.", "Escassez de água"], "Escassez de água", ""),
	new Question("(Enem-2010) Os frutos são exclusivos das angiospermas, e a dispersão das sementes dessas plantas é muito importante para garantir seu sucesso reprodutivo, pois permite a conquista de novos territórios. A dispersão é favorecida por certas características dos frutos (ex: cores fortes e vibrantes, gosto e odor agradáveis, polpa suculenta) e das sementes (Ex: presença de ganchos e outras estruturas fixadoras que se aderem às penas e pelos de animais, tamanho reduzido, leveza e presença de expansões semelhantes a asas). Nas matas brasileiras, os animais da fauna silvestre têm uma importante contribuição na dispersão de sementes e, portanto, na manutenção da diversidade da flora.</br>Das características de frutos e sementes apresentadas, quais estão diretamente associadas a um mecanismo de atração de aves e mamíferos? ", ["Ganchos que permitem a adesão aos pelos e penas.", "Estruturas fixadoras que se aderem às asas das aves.", "Frutos com poupa suculenta que fornecem energia aos dispersores.", "Leveza e tamanho reduzido das sementes, que favorecem a flutuação."], "Frutos com poupa suculenta que fornecem energia aos dispersores.", "imagens\\imagens-questoes\\fase3-questao6.png"),
	new Question("Você já observou uma cobertura vegetal muito pequena em muros e rochas? Esse “tapete verde”, muito comum em lugares úmidos, é formado por musgos - um tipo de briófita, plantas que dependem da água para reproduzir, encontradas preferencialmente em locais úmidos e com sombra, como barrancos, encostas de rios e cachoeiras.</br>Com base no esquema abaixo, sobre o ciclo de vida de um musgo, correlacione, no quadro ao lado, os algarismos de 1 a 4 que definem corretamente cada uma das fases enumeradas no ciclo reprodutivo dessas briófitas.</br>Assinale a alternativa que representa a sequência numérica correta das fases observadas no ciclo reprodutivo do musgo.", ["4, 2, 3 e 1.", "1, 2, 3 e 4.", "4, 3, 2 e 1.", "1, 3, 2 e 4."], "4, 2, 3 e 1.", ""),
	new Question("Os manguezais são ecossistemas encontrados na costa brasileira, nas regiões de encontro entre ás aguas dos rios e dos oceanos, onde algumas espécies da vida marinha se reproduzem. Apresentam vegetação formada basicamente de três espécies de árvores: mangue vermelho (Rhizophora mangle), mangue seriba (Avicennia schaueriana) e mangue branco (Laguncularia racemosa), adaptadas ao solo típico desse ecossistema, que é úmido, salgado, lodoso, pobre em oxigênio e muito rico em nutrientes, e que por isso, apresentam uma serie de adaptações a sua sobrevivência.</br>Dentre as adaptações encontradas na vegetação nativa deste ecossistema, estão presentes", ["pneumatóforos ou raizes respiratórias, que auxiliam na captura de oxigênio do ar.", "caules retorcidos e casca grossa, devido as altas concentrações salinas do solo.", "folhas transformadas em espinhos, que diminuem a perda de água para o ambiente.", "dormência prolongada da semente, que aumentam a sobrevivência do embrião no solo."], "", ""),
	new Question("Em determinados ecossistemas, como a caatinga brasileira, são encontradas plantas xerófitas (plantas de clima seco), como por exemplo, as cactáceas. Essas plantas apresentam folhas transformadas em espinhos e caule suculento e clorofilados, adaptados a armazenagem de água e a fotossíntese.</br>O tipo de caule presente nesse tipo de planta, recebe o nome de:", ["Bulbo.", "Rizoma.", "Cladódio.", "Xilopódio."], "Cladódio.", ""),
	new Question("A tabela abaixo relaciona algumas características de três grupos de plantas:</br> preenchimento correto da tabela deve substituir os números I, II e III, respectivamente, por:", ["Briófitas, gimnospermas e angiospermas.", "Pteridófitas, gimnospermas e angiospermas.", "Briófitas, pteridófitas e angiospermas.", "Briófitas, pteridófitas e gimnospermas."], "Briófitas, gimnospermas e angiospermas.", "imagens\\imagens-questoes\\fase3-questao9.png"),
	new Question("Um horticultor deseja obter indivíduos geneticamente idênticos (clones) a uma samambaia comercialmente valiosa. Para alcançar esse objetivo ele deve:", ["Cultivar os esporos produzidos por essa samambaia.", "Induzir artificialmente a autofecundação dessa samambaia.", "Implantar núcleos de esporos dessa samambaia em oosferas anucleadas de outras plantas.", "Obter fragmentos de rizoma (caule) dessa samambaia e cultivá-los."], "Obter fragmentos de rizoma (caule) dessa samambaia e cultivá-los.", "")
	],

	//fase4
	[
	]
];

