var questions = [
	new Question("Briófitas e pteridófitas apresentam várias características em comum, mas também diferem em muitos aspectos.</br>Assinale a característica que pertence a apenas um desses grupos de plantas.", ["Crescer preferencialmente em solos úmidos e sombreados.", "Necessitar de água para reproduzir-se.", "Não ter flores, sementes e frutos.", "Ser portadora de tecidos de transporte."], "Ser portadora de tecidos de transporte.", ""),
	new Question("Considere os seguintes organismos:</br>I.Algas</br>II.Briófitas</br>III.Pteridófitas</br>IV.Angiospermas</br>Gametas masculinos flagelados, que necessitam de água para encontrar os gametas femininos, são encontrados SOMENTE em:", ["I e II", "III e IV", "I, II e III", "I, III e IV"], "I e II", ""),
	new Question("Neste ano o Jardim Botânico do Rio de Janeiro completa 200 anos de existência. Nele estão situados acervos de mais de 8.000 espécies de plantas nacionais e de várias partes do mundo. O Jardim Botânico foi expandido em 15.000m2 e as estufas das orquídeas, bromélias, cactos e das plantas insetívoras foram reformadas. Este último grupo de plantas, também conhecido como plantas carnívoras, chama muito a atenção por poder obter nutrientes dos animais que capturam e digerem. Entretanto, os organismos do Reino Plantae são classificados quanto a sua nutrição como autótrofos.</br>Os organismos autótrofos são aqueles que sintetizam moléculas orgânicas a partir de:", ["água e glicose", "substâncias orgânicas", "água e CO2", "água, O2 e proteínas"], "água e CO2",""),
	new Question("Uma fruta podre no cesto pode estragar todo o resto.", ["Etileno", "Auxina", "Citocinina", "Giberelina"], "Etileno", ""),
	new Question("São processos biológicos relacionados diretamente a transformações energéticas celulares:", ["respiração e fotossíntese.", "digestão e excreção.", "respiração e excreção.", "digestão e osmose."], "respiração e fotossíntese.", ""),
	new Question("As trocas gasosas, ao nível das folhas, ocorrem através de numerosas aberturas epidérmicas denominadas:", ["Parênquimas", "Estômatos", "Células-guarda", "Acúleos"], "Estômatos", ""),
	new Question("Em pesquisas desenvolvidas com eucaliptos, constatou-se que a partir das gemas de um único ramo pode-se gerar cerca de 200.000 novas plantas, em aproximadamente duzentos dias; enquanto os métodos tradicionais permitem a obtenção de apenas cerca de cem mudas a partir de um mesmo ramo.</br>A cultura de tecido é feita a partir:", ["de células meristemáticas.", "de células da epiderme.", "de células do lenho.", "de células do súber."], "de células meristemáticas.", ""),
	new Question("As células vegetais jovens (meristemáticas) possuem inúmeras e pequenas bolsas membranosas que se fundem com o amadurecimento celular e em cujo interior encontra-se uma solução aquosa de proteínas, açúcares, íons inorgânicos, pigmentos hidrossolúveis e enzimas hidrolíticas.</br>Essas estruturas são:", ["os vacúolos.", "os lisossomos.", "os cloroplastos.", "o complexo de Golgi."], "os vacúolos.", ""),
	new Question("No corpo de uma planta superior, qual é o tecido que apresenta numerosas mitoses, sendo sempre formado por células indiferenciadas?", ["parênquima paliçádico", "colênquima angular", "colênquima tabular", "meristema primário"], "meristema primário", ""),
	new Question("Cortando-se, em forma de anel, a casca do caule de uma planta, a parte situada entre o corte e a raiz não é nutrida e morre.</br>O fluxo de seiva elaborada, com substâncias nutritivas, ocorre, das folhas para a raiz, no:", ["Xilema", "Meristema", "Floema", "Parênquima"], "Floema", ""),
	new Question("São importantes tecidos de sustentação dos vegetais:", ["Floema e xilema.", "Súber e ritidoma.", "Colênquima e esclerênquima.", "Parênquima de reserva."], "Colênquima e esclerênquima.")
];